services:
  Kobrad-node-1:
    build: .
    container_name: kobrad-node-1
    ports:
      - "16118:44447"  # P2P port
      - "17118:44448"  # RPC port
    command: ["--rpclisten=0.0.0.0:44448", "--listen=0.0.0.0:44447", "--utxoindex", "--addpeer=89.155.26.12:44447", "--addpeer=84.247.131.3:44447", "--addpeer=194.233.66.230:44447", "--addpeer=213.199.56.32:44447", "--addpeer=45.90.123.219:44447", "--addpeer=45.90.123.88:44447", "--addpeer=4.228.58.100:44447", "--addpeer=172.214.141.215:44447"]

  Kobrad-node-2:
    build: .
    container_name: kobrad-node-2
    ports:
      - "16119:44447"
      - "17119:44448"
    command: ["--rpclisten=0.0.0.0:44448", "--listen=0.0.0.0:44447", "--utxoindex", "--addpeer=89.155.26.12:44447", "--addpeer=84.247.131.3:44447", "--addpeer=194.233.66.230:44447", "--addpeer=213.199.56.32:44447", "--addpeer=45.90.123.219:44447", "--addpeer=45.90.123.88:44447", "--addpeer=4.228.58.100:44447", "--addpeer=172.214.141.215:44447"]

  Kobrad-node-3:
    build: .
    container_name: kobrad-node-3
    ports:
      - "16122:44447"
      - "17123:44448"
    command: ["--rpclisten=0.0.0.0:44448", "--listen=0.0.0.0:44447", "--utxoindex", "--addpeer=89.155.26.12:44447", "--addpeer=84.247.131.3:44447", "--addpeer=194.233.66.230:44447", "--addpeer=213.199.56.32:44447", "--addpeer=45.90.123.219:44447", "--addpeer=45.90.123.88:44447", "--addpeer=4.228.58.100:44447", "--addpeer=172.214.141.215:44447"]
